import the required libraries first

In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC


Load the dataset 

In [38]:
data=pd.read_csv('.\diabetes.csv')
data.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Split the data into input and target features 

In [39]:
X=data.drop('Outcome',axis=1)
y=data['Outcome']

print(X)
print(y)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


split the data into two subsets :
- Subset 1(Train Sets)
- Subset 2(Validation Set/Hold Out Set)

In [40]:
from sklearn.model_selection import train_test_split
train,val_train,test,val_test=train_test_split(X,y,test_size=0.5,random_state=44)

Split the train set further into train and test set 

In [41]:
X_train,X_test,y_train,y_test=train_test_split(train,test,test_size=0.2,random_state=44)

### Model 1-Implemantation of KNeighbour Classifier 

In [42]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
y_pred_knn

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_knn)

0.6363636363636364

### Model 2- Implementation of SVC Classifier

In [44]:
svc=SVC()
svc.fit(X_train,y_train)
y_pred_svc=svc.predict(X_test)
y_pred_svc  

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [45]:
accuracy_score(y_test,y_pred_svc)

0.6753246753246753

Predictions of the model in the validation set 

In [46]:
prediction_val1=knn.predict(val_train)
prediction_val2=svc.predict(val_train)

print('KNN Prediction\n',prediction_val1)
print('svc Prediction\n',prediction_val2)


KNN Prediction
 [0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0
 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0
 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0
 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1
 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
svc Prediction
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0

In [47]:
predict_val=np.column_stack((prediction_val1,prediction_val2))
predict_val.shape

(384, 2)

In [48]:
predict_test1=knn.predict(X_test)
predict_test2=svc.predict(X_test)
predict_test=np.column_stack((predict_test1,predict_test2))
predict_test

array([[1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0,

### Input featurs are the predictions of the model M1(KNN) and model M2(SVC) stored inside the predict_val (input features) for the Random Forest Classifier 

In [49]:
print('Predict_val\n',predict_val.shape)
print('Val_test \n',val_test.shape)

Predict_val
 (384, 2)
Val_test 
 (384,)


In [50]:
from sklearn.ensemble import RandomForestClassifier
rand_clf=RandomForestClassifier()
rand_clf.fit(predict_val,val_test)


RandomForestClassifier()

In [51]:
rand_clf.score(predict_test,y_test)

0.6753246753246753

**Hyperparameter Tuning**

In [52]:
grid_param={
"n_estimators":[100,300,500],
"max_features":["auto",'log2'],
"criterion":["gini","entropy"],
"min_samples_split":[4,5,6,7,8],
"min_samples_leaf":[1,2,3,4,5 ]
}

from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(estimator=rand_clf,param_grid=grid_param,cv=5,n_jobs=-1,verbose=3 )


In [53]:
grid_search.fit(predict_val,val_test)
print(grid_search.best_params_)

Fitting 5 folds for each of 300 candidates, totalling 1500 fits


c:\Users\krish\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
750 fits failed out of a total of 1500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
388 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\krish\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\krish\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\krish\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params


{'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 100}


- These come out to be the best parameters : **{'criterion': 'gini', 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 100}**
Future Work : we rebuild the model using these parameters to get the best results.